### ISSUE TITLE
초기세팅(프론트)

### ISSUE THREAD

**Issue by sojeong0302** [sojeong0302/ImPro#1]
## TYPE
- [ ] 새로운 기능 추가✨
- [ ] 기능 삭제🔥
- [ ] 버그 수정🐛
- [ ] CSS 등 사용자 UI 디자인 변경🎨
- [ ] 코드 리팩토링💡
- [ ] 주석 추가 및 삭제📚
- [ ] 문서 수정🍙
- [ ] 테스트 관련 작업🎄
- [ ] 파일 혹은 폴더명 수정📃
- [ ] 파일 혹은 폴더 삭제🔨
- [x] 설정 파일 관련 (패키지, 라이브러리 추가)⚙

## Description
설명을 작성해주세요.

## Todo
- [x] react 설치

## ETC
프론트 작업 끝나고 백엔드 작업 들어 갈거라 나중에 추가로 세팅

## Period
2024.12.24 ~ 2024.12.24
