### ISSUE TITLE
main 페이지 레이아웃🎨

### ISSUE THREAD

**Issue by sojeong0302** [sojeong0302/ImPro#2]
## TYPE
- [ ] 새로운 기능 추가✨
- [ ] 기능 삭제🔥
- [ ] 버그 수정🐛
- [x] CSS 등 사용자 UI 디자인 변경🎨
- [ ] 코드 리팩토링💡
- [ ] 주석 추가 및 삭제📚
- [ ] 문서 수정🍙
- [ ] 테스트 관련 작업🎄
- [ ] 파일 혹은 폴더명 수정📃
- [ ] 파일 혹은 폴더 삭제🔨
- [ ] 설정 파일 관련 (패키지, 라이브러리 추가)⚙

## Description
설명을 작성해주세요.

## Todo
- [ ] 헤더
- [ ] 사진 첨부
- [ ] 레이아웃

## ETC
기타사항

## Period
2024.12.28 ~ 2024.12.31
